//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for SortParam.
const (
	SortParamAsc  SortParam = "asc"
	SortParamDesc SortParam = "desc"
)

// Valid indicates whether the value is a known member of the SortParam enum.
func (e SortParam) Valid() bool {
	switch e {
	case SortParamAsc:
		return true
	case SortParamDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountBlocksParamsSort.
const (
	ListAccountBlocksParamsSortAsc  ListAccountBlocksParamsSort = "asc"
	ListAccountBlocksParamsSortDesc ListAccountBlocksParamsSort = "desc"
)

// Valid indicates whether the value is a known member of the ListAccountBlocksParamsSort enum.
func (e ListAccountBlocksParamsSort) Valid() bool {
	switch e {
	case ListAccountBlocksParamsSortAsc:
		return true
	case ListAccountBlocksParamsSortDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountTransactionsParamsSort.
const (
	ListAccountTransactionsParamsSortAsc  ListAccountTransactionsParamsSort = "asc"
	ListAccountTransactionsParamsSortDesc ListAccountTransactionsParamsSort = "desc"
)

// Valid indicates whether the value is a known member of the ListAccountTransactionsParamsSort enum.
func (e ListAccountTransactionsParamsSort) Valid() bool {
	switch e {
	case ListAccountTransactionsParamsSortAsc:
		return true
	case ListAccountTransactionsParamsSortDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListMomentumsParamsSort.
const (
	ListMomentumsParamsSortAsc  ListMomentumsParamsSort = "asc"
	ListMomentumsParamsSortDesc ListMomentumsParamsSort = "desc"
)

// Valid indicates whether the value is a known member of the ListMomentumsParamsSort enum.
func (e ListMomentumsParamsSort) Valid() bool {
	switch e {
	case ListMomentumsParamsSortAsc:
		return true
	case ListMomentumsParamsSortDesc:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Address                  string  `json:"address"`
	BlockCount               int64   `json:"block_count"`
	Delegate                 *string `json:"delegate,omitempty"`
	DelegationStartTimestamp *int64  `json:"delegation_start_timestamp,omitempty"`
	FirstActiveAt            *int64  `json:"first_active_at,omitempty"`

	// GenesisQsrBalance Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	GenesisQsrBalance Amount `json:"genesis_qsr_balance"`

	// GenesisZnnBalance Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	GenesisZnnBalance Amount  `json:"genesis_znn_balance"`
	LastActiveAt      *int64  `json:"last_active_at,omitempty"`
	PublicKey         *string `json:"public_key,omitempty"`

	// QsrReceived Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	QsrReceived Amount `json:"qsr_received"`

	// QsrSent Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	QsrSent Amount `json:"qsr_sent"`

	// ZnnReceived Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	ZnnReceived Amount `json:"znn_received"`

	// ZnnSent Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	ZnnSent Amount `json:"znn_sent"`
}

// AccountBlock A transaction (account-block in Zenon's dual-ledger model). One
// block is either a send (block_type 1..4) or a receive (5..8); a
// complete transaction is the matched (send, receive) pair.
type AccountBlock struct {
	Address string `json:"address"`

	// Amount Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	Amount       Amount  `json:"amount"`
	BlockType    int     `json:"block_type"`
	Data         *string `json:"data,omitempty"`
	DescendantOf *string `json:"descendant_of,omitempty"`
	Hash         string  `json:"hash"`
	Height       int64   `json:"height"`

	// Input Decoded contract inputs (JSON object) when the indexer recognized the method.
	Input              *map[string]string `json:"input,omitempty"`
	Method             *string            `json:"method,omitempty"`
	MomentumHash       string             `json:"momentum_hash"`
	MomentumHeight     int64              `json:"momentum_height"`
	MomentumTimestamp  int64              `json:"momentum_timestamp"`
	PairedAccountBlock *string            `json:"paired_account_block,omitempty"`
	ToAddress          *string            `json:"to_address,omitempty"`
	TokenStandard      *string            `json:"token_standard,omitempty"`
}

// AccountBlockList defines model for AccountBlockList.
type AccountBlockList struct {
	Data       []AccountBlock `json:"data"`
	Pagination Pagination     `json:"pagination"`
}

// Amount Raw int64 token amount (no decimals applied) serialized as a
// JSON string. Strings avoid JavaScript Number precision loss for
// values above 2^53-1 — ZNN total supply already exceeds that.
type Amount = string

// Balance defines model for Balance.
type Balance struct {
	Address string `json:"address"`

	// Balance Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	Balance              Amount `json:"balance"`
	LastUpdatedTimestamp int64  `json:"last_updated_timestamp"`
	TokenStandard        string `json:"token_standard"`
}

// BalanceList defines model for BalanceList.
type BalanceList struct {
	Data []Balance `json:"data"`
}

// BalancePage defines model for BalancePage.
type BalancePage struct {
	Data       []Balance  `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Momentum defines model for Momentum.
type Momentum struct {
	Hash          string  `json:"hash"`
	Height        int64   `json:"height"`
	Producer      string  `json:"producer"`
	ProducerName  *string `json:"producer_name,omitempty"`
	ProducerOwner *string `json:"producer_owner,omitempty"`
	Timestamp     int64   `json:"timestamp"`
	TxCount       int     `json:"tx_count"`
}

// MomentumList defines model for MomentumList.
type MomentumList struct {
	Data       []Momentum `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`

	// Total Total rows matching the query across all pages.
	Total int64 `json:"total"`
}

// Pillar defines model for Pillar.
type Pillar struct {
	EpochExpectedMomentums       *int   `json:"epoch_expected_momentums,omitempty"`
	EpochProducedMomentums       *int   `json:"epoch_produced_momentums,omitempty"`
	GiveDelegateRewardPercentage *int   `json:"give_delegate_reward_percentage,omitempty"`
	GiveMomentumRewardPercentage *int   `json:"give_momentum_reward_percentage,omitempty"`
	IsRevocable                  bool   `json:"is_revocable"`
	IsRevoked                    bool   `json:"is_revoked"`
	Name                         string `json:"name"`
	OwnerAddress                 string `json:"owner_address"`
	ProducedMomentumCount        *int64 `json:"produced_momentum_count,omitempty"`
	ProducerAddress              string `json:"producer_address"`
	Rank                         int    `json:"rank"`
	RevokeCooldown               *int   `json:"revoke_cooldown,omitempty"`
	RevokeTimestamp              *int64 `json:"revoke_timestamp,omitempty"`

	// SlotCostQsr Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	SlotCostQsr    Amount   `json:"slot_cost_qsr"`
	SpawnTimestamp *int64   `json:"spawn_timestamp,omitempty"`
	VotingActivity *float32 `json:"voting_activity,omitempty"`

	// Weight Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	Weight          Amount `json:"weight"`
	WithdrawAddress string `json:"withdraw_address"`
}

// PillarDelegator defines model for PillarDelegator.
type PillarDelegator struct {
	Address                  string `json:"address"`
	DelegationStartTimestamp int64  `json:"delegation_start_timestamp"`
}

// PillarDelegatorList defines model for PillarDelegatorList.
type PillarDelegatorList struct {
	Data       []PillarDelegator `json:"data"`
	Pagination Pagination        `json:"pagination"`
}

// PillarList defines model for PillarList.
type PillarList struct {
	Data       []Pillar   `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Problem RFC 7807 problem details.
type Problem struct {
	// Code Stable application-level error code (extension).
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`
	Status   int32   `json:"status"`

	// Title A short, human-readable summary.
	Title string `json:"title"`

	// Type A URI reference identifying the problem type.
	Type string `json:"type"`
}

// Sentinel defines model for Sentinel.
type Sentinel struct {
	Active                bool    `json:"active"`
	IsRevocable           bool    `json:"is_revocable"`
	Owner                 string  `json:"owner"`
	RegistrationTimestamp int64   `json:"registration_timestamp"`
	RevokeCooldown        *string `json:"revoke_cooldown,omitempty"`
}

// SentinelList defines model for SentinelList.
type SentinelList struct {
	Data       []Sentinel `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Status Indexer sync state derived from the database.
type Status struct {
	// IndexerLagSeconds Server clock minus latest_timestamp. Grows when the indexer falls behind.
	IndexerLagSeconds int64 `json:"indexer_lag_seconds"`

	// LatestHeight Height of the most-recently-indexed momentum (0 if empty).
	LatestHeight int64 `json:"latest_height"`

	// LatestTimestamp Unix-seconds timestamp of the latest momentum.
	LatestTimestamp int64  `json:"latest_timestamp"`
	Version         string `json:"version"`
}

// Token defines model for Token.
type Token struct {
	Decimals            int     `json:"decimals"`
	Domain              *string `json:"domain,omitempty"`
	HolderCount         int64   `json:"holder_count"`
	IsBurnable          bool    `json:"is_burnable"`
	IsMintable          bool    `json:"is_mintable"`
	IsUtility           bool    `json:"is_utility"`
	LastUpdateTimestamp int64   `json:"last_update_timestamp"`

	// MaxSupply Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	MaxSupply     Amount `json:"max_supply"`
	Name          string `json:"name"`
	Owner         string `json:"owner"`
	Symbol        string `json:"symbol"`
	TokenStandard string `json:"token_standard"`

	// TotalBurned Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	TotalBurned Amount `json:"total_burned"`

	// TotalSupply Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	TotalSupply      Amount `json:"total_supply"`
	TransactionCount int64  `json:"transaction_count"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	Data       []Token    `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// SortParam defines model for SortParam.
type SortParam string

// RateLimited RFC 7807 problem details.
type RateLimited = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAccountBlocksParams defines parameters for ListAccountBlocks.
type ListAccountBlocksParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort direction over the endpoint's documented sort column. Defaults vary per endpoint.
	Sort *ListAccountBlocksParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListAccountBlocksParamsSort defines parameters for ListAccountBlocks.
type ListAccountBlocksParamsSort string

// ListAccountTransactionsParams defines parameters for ListAccountTransactions.
type ListAccountTransactionsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort direction over the endpoint's documented sort column. Defaults vary per endpoint.
	Sort *ListAccountTransactionsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListAccountTransactionsParamsSort defines parameters for ListAccountTransactions.
type ListAccountTransactionsParamsSort string

// ListMomentumsParams defines parameters for ListMomentums.
type ListMomentumsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort direction over the endpoint's documented sort column. Defaults vary per endpoint.
	Sort *ListMomentumsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListMomentumsParamsSort defines parameters for ListMomentums.
type ListMomentumsParamsSort string

// ListPillarsParams defines parameters for ListPillars.
type ListPillarsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize       *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`
	IncludeRevoked *bool          `form:"include_revoked,omitempty" json:"include_revoked,omitempty"`
}

// ListPillarDelegatorsParams defines parameters for ListPillarDelegators.
type ListPillarDelegatorsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListSentinelsParams defines parameters for ListSentinels.
type ListSentinelsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize        *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`
	IncludeInactive *bool          `form:"include_inactive,omitempty" json:"include_inactive,omitempty"`
}

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListTokenHoldersParams defines parameters for ListTokenHolders.
type ListTokenHoldersParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List account-blocks (transactions)
	// (GET /api/v1/account_blocks)
	ListAccountBlocks(w http.ResponseWriter, r *http.Request, params ListAccountBlocksParams)
	// Get an account-block by hash
	// (GET /api/v1/account_blocks/{hash})
	GetAccountBlock(w http.ResponseWriter, r *http.Request, hash string)
	// Get account info
	// (GET /api/v1/accounts/{address})
	GetAccount(w http.ResponseWriter, r *http.Request, address string)
	// List balances for an account
	// (GET /api/v1/accounts/{address}/balances)
	GetAccountBalances(w http.ResponseWriter, r *http.Request, address string)
	// List transactions involving an address
	// (GET /api/v1/accounts/{address}/transactions)
	ListAccountTransactions(w http.ResponseWriter, r *http.Request, address string, params ListAccountTransactionsParams)
	// List momentums
	// (GET /api/v1/momentums)
	ListMomentums(w http.ResponseWriter, r *http.Request, params ListMomentumsParams)
	// Get the most-recently-indexed momentum
	// (GET /api/v1/momentums/latest)
	GetLatestMomentum(w http.ResponseWriter, r *http.Request)
	// Get a momentum by height
	// (GET /api/v1/momentums/{height})
	GetMomentumByHeight(w http.ResponseWriter, r *http.Request, height int64)
	// List pillars
	// (GET /api/v1/pillars)
	ListPillars(w http.ResponseWriter, r *http.Request, params ListPillarsParams)
	// Get a pillar by name
	// (GET /api/v1/pillars/{name})
	GetPillar(w http.ResponseWriter, r *http.Request, name string)
	// List delegators for a pillar
	// (GET /api/v1/pillars/{name}/delegators)
	ListPillarDelegators(w http.ResponseWriter, r *http.Request, name string, params ListPillarDelegatorsParams)
	// List sentinels
	// (GET /api/v1/sentinels)
	ListSentinels(w http.ResponseWriter, r *http.Request, params ListSentinelsParams)
	// Indexer sync status
	// (GET /api/v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// List ZTS tokens
	// (GET /api/v1/tokens)
	ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams)
	// Get a ZTS token by ZTS identifier
	// (GET /api/v1/tokens/{token_standard})
	GetToken(w http.ResponseWriter, r *http.Request, tokenStandard string)
	// Richlist for a token
	// (GET /api/v1/tokens/{token_standard}/holders)
	ListTokenHolders(w http.ResponseWriter, r *http.Request, tokenStandard string, params ListTokenHoldersParams)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccountBlocks operation middleware
func (siw *ServerInterfaceWrapper) ListAccountBlocks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountBlocksParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountBlocks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBlock operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBlock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBlock(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, address)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBalances operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBalances(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBalances(w, r, address)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccountTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListAccountTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountTransactionsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountTransactions(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMomentums operation middleware
func (siw *ServerInterfaceWrapper) ListMomentums(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMomentumsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMomentums(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLatestMomentum operation middleware
func (siw *ServerInterfaceWrapper) GetLatestMomentum(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestMomentum(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMomentumByHeight operation middleware
func (siw *ServerInterfaceWrapper) GetMomentumByHeight(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "height" -------------
	var height int64

	err = runtime.BindStyledParameterWithOptions("simple", "height", r.PathValue("height"), &height, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "height", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMomentumByHeight(w, r, height)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPillars operation middleware
func (siw *ServerInterfaceWrapper) ListPillars(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPillarsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "include_revoked" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_revoked", r.URL.Query(), &params.IncludeRevoked, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include_revoked"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_revoked", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPillars(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPillar operation middleware
func (siw *ServerInterfaceWrapper) GetPillar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPillar(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPillarDelegators operation middleware
func (siw *ServerInterfaceWrapper) ListPillarDelegators(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPillarDelegatorsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPillarDelegators(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSentinels operation middleware
func (siw *ServerInterfaceWrapper) ListSentinels(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSentinelsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "include_inactive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_inactive", r.URL.Query(), &params.IncludeInactive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include_inactive"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_inactive", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSentinels(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTokens operation middleware
func (siw *ServerInterfaceWrapper) ListTokens(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokensParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokens(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToken operation middleware
func (siw *ServerInterfaceWrapper) GetToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token_standard" -------------
	var tokenStandard string

	err = runtime.BindStyledParameterWithOptions("simple", "token_standard", r.PathValue("token_standard"), &tokenStandard, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token_standard", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToken(w, r, tokenStandard)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTokenHolders operation middleware
func (siw *ServerInterfaceWrapper) ListTokenHolders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token_standard" -------------
	var tokenStandard string

	err = runtime.BindStyledParameterWithOptions("simple", "token_standard", r.PathValue("token_standard"), &tokenStandard, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token_standard", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokenHoldersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokenHolders(w, r, tokenStandard, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/account_blocks", wrapper.ListAccountBlocks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/account_blocks/{hash}", wrapper.GetAccountBlock)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/accounts/{address}", wrapper.GetAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/accounts/{address}/balances", wrapper.GetAccountBalances)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/accounts/{address}/transactions", wrapper.ListAccountTransactions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums", wrapper.ListMomentums)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums/latest", wrapper.GetLatestMomentum)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums/{height}", wrapper.GetMomentumByHeight)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/pillars", wrapper.ListPillars)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/pillars/{name}", wrapper.GetPillar)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/pillars/{name}/delegators", wrapper.ListPillarDelegators)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sentinels", wrapper.ListSentinels)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tokens", wrapper.ListTokens)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tokens/{token_standard}", wrapper.GetToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tokens/{token_standard}/holders", wrapper.ListTokenHolders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx5bxtHsv8qhdkFImF5SZZzKAgC2c7GDhLHz1SwQEwt2Zwpcjrq6R5391CiBAH7Id5neB9sP8lDH3Ny",
	"eDmWLL+3/sfiTB9V1b86u8jbIBRJKjhyrYLT2yAlkiSoUdpPb8gc35gn5kOEKpQ01VTw4DQ46k6JwghS",
	"MkfgWTJF2YMXOCMZ0wq0gKMe/Jrprph1JeFzhJCRJMUIFGXINVv2gk5AzUrvM5TLoBNwkmBwGpgFg06g",
	"whgT4va1iwanR50Ar0mSMlTB6buji06QUE6TLLGv9DI10ynXOEcZ3N11LPlDerOOhVcaEwUpSstEQT08",
	"HXQgIddmZTgeDP4EH2NFb9Yw83RQ4+bpwLDjNg1OjweDrcwNhdRrGDOvIKISQ/MAxAIl6BgBeZQKyvUX",
	"CiIRZglybRgxo0PBsoRXTnBB5NLKJp+0jk8zvcYickP0u4CoMOhYyoKLggOlJeXz4M5wIFGlgiu0UHtL",
	"NP5ME6oxMh9DwTVybf4kacpoSAwr/VSKKcPkb38ow+htZde/SpwFp8Ff+iWe++6t6r9xs9yudVGdCwEJ",
	"4UuQ+D5DpRXMhBEWVaCy6R8Y6l5w1wl+4yTTsZD05mHJ+4UqRfkchATKF4TRCKZIpDlPcYm8Z5Hg1zHb",
	"nIWhyBxdqRQpSk2deEkUSVT2z8ZJdIIpE+HluJg4EzIh2qHty5NgFXyGSIZzorF1Of+SCj5Wmkg91jRB",
	"pUmS7rj6jEqlxyTUdIFjsitNc+SoqBq/V3I8JYzwELcJ/iyxPFcm33C+/2RGPoDcNJsyGo4vcdkqRMOF",
	"xBDpwgFuN0rMLOVxudsMw/D++5hZ++xjlf19RqXZ5F0Bxjr02k+h/WArJDR4qAihIcXSCAmr2IYRry/P",
	"DBmrdvQMtCRcEWdGD4gb3LVEA+XwO3LBjTHNCOsyjOYoIRERssMe/MpxxP1IBUh1jBIIKOQRHDi2DTVw",
	"1OudHBr9JuAphYOnvd7Xh98CGXEjU4Yaa4RQZa15QnQYYwQHZs1OPvsQUkJlb8SDzh4mgCS59u8GgJIB",
	"a/FLP3Z80WoviCZrbIUKkUeE67GYtY6IiYrbXyCdx7tqG+Vppr0QqBEiYW9qwmmlrETCCwxFhBEYuy9J",
	"qMEuqODgp+Gvr8Hh6RCuYuT2aCiP8BqlORMx58ZpuBNDHYuoF7QA0b1qpSQRxlFnyXitKMoR+8ikmLWv",
	"fTYAw2js1WE8zZVnhS4txptAZ12Y8RE8IrKN94bZsPw35dHKx6pIapAtwNOpmCKvAtusxM9UtbjXHODU",
	"hJRb1ahqdO6K/YiUZOnkO6ecOORtiRzKkU1hWYpqa7VyVuh9He9vyRVYALg4A5xw4IALiDCkCWEKbOCD",
	"0SEolJQwi3KijNWySuEOsQdD+78CshA0gp/IggztRvDaJg2QSgypMnaNCWXDr5GJdDJUQKZigXD8z6dP",
	"ukfw73/9N/z++jVooQkDlaUpWwJhEkm0BLwOESNjF4l2tq9ik4KjQfnPiCElWqM0fP6z+/27Qfebi7/9",
	"NeisAvRZGQnsEU19UPiQpRHRGO2ti/vqUIn3xsyS8LUUtQHIi+gjaEUu7BWFaAP2BlJM0ndfpDyobr5E",
	"wnS8yorSRGeqmmmJy7YMq76nn9W20S/eVq5ulXucqjJ9OT0hT45ns3//639adq365Wqyfvzk5OlFZxXR",
	"RZI7aPU0UkRZiLJJw83R+/fr9s/njF1+erthhLjibu1V11RVwyofX+V2pI2ZFvW8LvOqyjJPLlpT+pqz",
	"yz2U93JV51asWpHQpoP9CNpZYOTT6sSb2lZ1flKv+I0aUVv8kldm6qNtDabNxGrCVl3kufVDUlwpF4mb",
	"NN0EebY8AiSUxpsRxmxxSfXqLmmtPmxBhS+OVWtLjrxWYVHGiFwVFKYijMd4nWJoDHweKlXdWYV9N9rj",
	"bOvouUmC8/LAWOIVkdE4RRki1/581kwqIrYdJ1E1lrgQIZmy6oipEAwJr4y4xKj9/VoDYe3CxtB1RRx7",
	"lU8KA7RpC0n4ZTvnjqlxKASLxBXfOGjfeEIxocehUNqk27vHMColV3zvzRZCUz53pROql7VZMyaILme5",
	"CrOZdFX4l91Iu6I6jiS52iDshpLVj7/luFoW9Wjyx9ZAZ0F0U741jK5X4RdOn4TcLxL9k4W4tZHjhnV3",
	"4OEjOKOmVD6xT7LUfDS2PjU3vhi9mhL+/Tl89fXgK/BFbohQE8qsZ6szHYoIWy4ltNEFqJTLuwwXyACl",
	"FBLMJDjAa43cJIOHDYcZZNUKfFvc58hpK+LFWUJ41ySKlgK8ThlxEgCVYkhnNAQtXNFfhGEmJfIQe20Z",
	"IeUmYQqxbZvf3r4CiTO0s4FGyDWdLfOwoNipvkOhhZmkbRtWgv1SGCeDo0bs8OS4PfykmrXSqmIhdacp",
	"GZUlCZHLpuh/2yb6vA64n0RyHJnZzS3JVGT6dMqMMb3YJqUGzn2Jx/He2ZT4DA1BHFmLWbXV/I1hxYbA",
	"Y31eIXFOlZbOeO7rLtf7/U2OLFi764qX8lxvEtVHMHOF1D+toRsWmtW4Ffa1W7XkIRjwIEQo6QIjmEmR",
	"WOiaHaZE4art85XfMSPzscJQ8KhliyHKBUoI7e1AQnmmgBGNquJJe/CjTS1WSsozwpiCKcaURw2tebpb",
	"Tuq3KvP0OnEv7XMQM1eyFkp3JYb2qrvriIggj3rhYAB0Bpikenm4a4qzOeVvCmKVwN84ve562UIxLifY",
	"zS8obBK1Z/6+QKk8GKvmKcLF9opLXc4tnHVa0VJu2obac3GJLblvXpRtzwUikRDK229RBItQ7pW9UDWe",
	"ZpJvzLsSyvXGAZmmzIf8q+8r9ce9jWRCrseuOLx7irA5EWx9o5bJVLAdrzVqpSutjm44v67+++bmJGPX",
	"7a7VZPdW3vvcz7pZ+4qhcse4ByCa3rdZVvZ5kRdYp4Rqp/BPNXJrR1hHWx1aNRw1JLUOQw3At/G8Vus+",
	"gutz2vsp/Z6BLoaZpHo5NCs6JlxPyVnmys3u09/zg//pH+dB8z705fD46ZddReccI/jpH+fGi2mMYEEJ",
	"TMIk6v9xpbtUqQwnPXhOpKSoYKKy6aQDE7xOzX+U6ElnxAmPgHD41ewOx70BqJSE2FWYEknMmhMVihQn",
	"EDJCE3e5Y4VhjYYltURlrHXq+mgon4m8U4eE9uB8wxIXiXdksjsXQSfIJPNT1Wm/P6c6zqa9UCT9wfWT",
	"L598029MWLkcfosk6grOlvDy/PwNnL15VbZc1eeWgQNY6ZMuUd38Tvl0xHGBcgl5XxQk1KRG7rY/4xFK",
	"ZoPnN0LpuUQFLqNiZCkyXe3oInrEc3YcDz3PFRUNbjyu+r0RH/G//AXMKZj4zGVo5uEZY0UPmHJkwKRP",
	"UtpfHPUn4AEIBJ65xiSDBupilsmZzxvsYpMRj5FEKHtg9UABkQg1JE2XBgokSihvg9K3ZlWJQNWIc+Gu",
	"JrsGeWWTGgwRYVfeDRMmtSm4L5XLPHguGPMtdBUBKAQxmynUfUYTquFg8n1K5vjd0SgbDI6/LEqz3z0d",
	"TGwfIRwPBodAeDTiEnUmueER+QKZSBEmtwYTp/Cu1+tddKBU3lO4NWvZR27Fjrv7vLub9EZ8SPmcYdeY",
	"nQp1fgMjfKfxvg2QLXMWf7CQMh/cX/YQ3DR3fztZ19A2gYO8BnAIV1THxVWv3yokUlqATow2GhW3OZj5",
	"wyVh5i+Xpk86YPV+xMNMaZHAxOT/E5hRZJHTcUZD5Mr6ZZ85UuOLg19enZfNh+ZDmec2VNtoYiWcOg0G",
	"vaPewPr1FDlJaXAaPLGP7JVwbE1hjuxad4N9M0drRYzxt8J5FQWngXEK1ft8Wy+s9NC+a7fm5ZB+2WN7",
	"19lpcNnRusOEskv07qLRcXk8GGxoZdyvhXGlQ6Kll9ErF0bAqLIJRq2hStlGy5PB0bq9CuL7tYKEmXT8",
	"zfZJ1QbTqhu0Z1R1gO8ujKh8LcQfcYNUOKjEDerQ+B8yd4WLOmwuzE7tkOrfxkTFd2uR9SPWgLWKK9uM",
	"a3BbqoO/KyyDAi0zrPbmNjOWh8JEa+ttjHnXrbE8VQH/CSgMTh6yP/e1qBPu7KKOiQZzFr37R+ePqK3P",
	"rFExXUJ+bbw7LlX/1tf4q6BshjrGUbiIxE/7QsGMiStIUEsaKjhgdIYm4obfX7/u/9fwLSjkup+3YXZG",
	"3Pb39k2ADvnVzyGkLFNQ3iy4yksP8g1PBidAbYY/4nkpJCYKbMgEYqpQLnyXnWfCeZF1OrWTOpVXHus1",
	"are2hIdQtDZ8+ldgouHPUKkq6pSf6gNpVEVuq1q0VX/6vpdKbVUkF/Ef1LPmDvj5hyDFlf9GQgHszogr",
	"IbULl/1AePHD8HkPXgudR5AY2Y650jSAXqY0JIwtR9wkwQoIxIRHs4zZ2pkNyTcrzbOcq4+lPA+pJdVO",
	"tRbQ/exjkvzkHnU0khNpoVEe8YcgtRrIbEVrIwq6stlYBZqVVneFNlMU0mQ9IU0p2uysAG6jQfdb8N+M",
	"ArNzGwwrkfZ5leb7wmLnP5H7/4nIvQpwoHwh2MLkqLbOUPTCbtSaWsvTRv0oRoKQEUqHdAdwOMgBPjFz",
	"J4c9MJAAHUuRzeMRN2o0yxiDMCaUO8/nSwsTmyy7D662MFmnIb8UtP6/zENrHY87Ibk4skcN4qRyrDlY",
	"y2ftaO27C6edYvmYzmNUuuuxWtyetcTf+U3kiNv420QcUoSolEni+BK8b1iiXhNM/GzJKhpKHwAN67LP",
	"lbvCzydALi1NTBYIU0QO+e2sEf3DhMnbb4j3weutQ9/Gkkh+pM+WL/N71R3KIvnQndK4D7q4fhCrtr2K",
	"0oDy4CFR6RsHqDMKBLjgXW7T+YUxGlZQn6OKAV5TpRUQ7Qs7ls+HSkRLMopQYrtOpbaTcHu84sdVoxVJ",
	"+CUQ+61M+/WtH65DlkWowLepjng+abrMY/ZvISVKweR7yu3gvKX1O6NlE9AC/AtjMJJ1ocsbT/QDBy5t",
	"v2nQ4KP9FxxmhCnsrLQv3KslqPSa7hTd+LN61LFNWpx7jur8SRum+7fmjDb6CN9Hu4tnyJu2H0WFIu//",
	"3WbknSQ+J1PqKK5U84zcH8yC+t2nS/DHvQfO+lHeZa52K4q7nBIVuC5fzZZ5VRsj12WMnqAOuDLeiE+X",
	"sL6nHs6Gz+GACT43AbpGnhlLbWvoh5tN6YuS9HvRhfutkNy/ptW/krDRnhYosJb1P6q3o2kvlcdVKj01",
	"21RQ+Q7h7SpXjKyFMK3tzrZEPuIHHK9M0ucVCM5sz3N1Ic6WK7HNiJfBDeWuT3o1upGojeaUi63Tz2HB",
	"4CMKdnK+Hk+0U2s636ifucT/rHrev0qoytHnSlA+q6tB0aG+1e34SsZKf7ZLGDpAdaVVuuOakSYt3cfw",
	"HXBxBd2VfvRJD56LJM10pQ1+xPN2NiBMcLQXTpFAlwDG1NUH7I/kABcRrqkH+Ub8+8SR26EFQc+dk640",
	"+z9W8Kx8LSGr1QJRkzp43H3eVvD8fj70V3+1knWlSdbaTTiwZZ4YWR56dGzFmkP95tIGK8bUK02mtjN3",
	"nQl0LYAPav/u01SVHcI75WX+tvUxG6oSGRWc+QctSOvf1pGwMUNzfdC7BKUr7eSPI1Xzjdxtvyd4aSux",
	"n1e7hfuRnzJGzOX9YClaATZjfcyHSsvnB6Gv70zYDlfaRcJmZuTfTbSr5QnaSp/FiBdVsRuUouwZ2GTr",
	"XnqC7hn1n29SVv39no1G1B3tow713tIwtrbepT3a27tWIMf2d35u1iL1jF2RZd7areB4MPCXw7cj/+XW",
	"UXA6CsTlKLib9OBFHoCFMYaXjTjNRGhGw79QMOnbn866mfRgmFH3VQJD7eXXChhdIEel3BrruoJeesLv",
	"ERP+N5Ba4DBEuaAhAlVADLm95gE1PJpnyFhPbAmc7Fy5yHWy0RskQsIgQtuyn7ifliy/NHLa7zMzIBZK",
	"n349+HoQ3F3c/W8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
