//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for SortParam.
const (
	SortParamAsc  SortParam = "asc"
	SortParamDesc SortParam = "desc"
)

// Valid indicates whether the value is a known member of the SortParam enum.
func (e SortParam) Valid() bool {
	switch e {
	case SortParamAsc:
		return true
	case SortParamDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountBlocksParamsSort.
const (
	ListAccountBlocksParamsSortAsc  ListAccountBlocksParamsSort = "asc"
	ListAccountBlocksParamsSortDesc ListAccountBlocksParamsSort = "desc"
)

// Valid indicates whether the value is a known member of the ListAccountBlocksParamsSort enum.
func (e ListAccountBlocksParamsSort) Valid() bool {
	switch e {
	case ListAccountBlocksParamsSortAsc:
		return true
	case ListAccountBlocksParamsSortDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListAccountTransactionsParamsSort.
const (
	ListAccountTransactionsParamsSortAsc  ListAccountTransactionsParamsSort = "asc"
	ListAccountTransactionsParamsSortDesc ListAccountTransactionsParamsSort = "desc"
)

// Valid indicates whether the value is a known member of the ListAccountTransactionsParamsSort enum.
func (e ListAccountTransactionsParamsSort) Valid() bool {
	switch e {
	case ListAccountTransactionsParamsSortAsc:
		return true
	case ListAccountTransactionsParamsSortDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListMomentumsParamsSort.
const (
	ListMomentumsParamsSortAsc  ListMomentumsParamsSort = "asc"
	ListMomentumsParamsSortDesc ListMomentumsParamsSort = "desc"
)

// Valid indicates whether the value is a known member of the ListMomentumsParamsSort enum.
func (e ListMomentumsParamsSort) Valid() bool {
	switch e {
	case ListMomentumsParamsSortAsc:
		return true
	case ListMomentumsParamsSortDesc:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Address                  string  `json:"address"`
	BlockCount               int64   `json:"block_count"`
	Delegate                 *string `json:"delegate,omitempty"`
	DelegationStartTimestamp *int64  `json:"delegation_start_timestamp,omitempty"`
	FirstActiveAt            *int64  `json:"first_active_at,omitempty"`

	// GenesisQsrBalance Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	GenesisQsrBalance Amount `json:"genesis_qsr_balance"`

	// GenesisZnnBalance Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	GenesisZnnBalance Amount  `json:"genesis_znn_balance"`
	LastActiveAt      *int64  `json:"last_active_at,omitempty"`
	PublicKey         *string `json:"public_key,omitempty"`

	// QsrReceived Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	QsrReceived Amount `json:"qsr_received"`

	// QsrSent Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	QsrSent Amount `json:"qsr_sent"`

	// ZnnReceived Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	ZnnReceived Amount `json:"znn_received"`

	// ZnnSent Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	ZnnSent Amount `json:"znn_sent"`
}

// AccountBlock A transaction (account-block in Zenon's dual-ledger model). One
// block is either a send (block_type 1..4) or a receive (5..8); a
// complete transaction is the matched (send, receive) pair.
type AccountBlock struct {
	Address string `json:"address"`

	// Amount Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	Amount       Amount  `json:"amount"`
	BlockType    int     `json:"block_type"`
	Data         *string `json:"data,omitempty"`
	DescendantOf *string `json:"descendant_of,omitempty"`
	Hash         string  `json:"hash"`
	Height       int64   `json:"height"`

	// Input Decoded contract inputs (JSON object) when the indexer recognized the method.
	Input              *map[string]string `json:"input,omitempty"`
	Method             *string            `json:"method,omitempty"`
	MomentumHash       string             `json:"momentum_hash"`
	MomentumHeight     int64              `json:"momentum_height"`
	MomentumTimestamp  int64              `json:"momentum_timestamp"`
	PairedAccountBlock *string            `json:"paired_account_block,omitempty"`
	ToAddress          *string            `json:"to_address,omitempty"`
	TokenStandard      *string            `json:"token_standard,omitempty"`
}

// AccountBlockList defines model for AccountBlockList.
type AccountBlockList struct {
	Data       []AccountBlock `json:"data"`
	Pagination Pagination     `json:"pagination"`
}

// Amount Raw int64 token amount (no decimals applied) serialized as a
// JSON string. Strings avoid JavaScript Number precision loss for
// values above 2^53-1 — ZNN total supply already exceeds that.
type Amount = string

// Balance defines model for Balance.
type Balance struct {
	Address string `json:"address"`

	// Balance Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	Balance              Amount `json:"balance"`
	LastUpdatedTimestamp int64  `json:"last_updated_timestamp"`
	TokenStandard        string `json:"token_standard"`
}

// BalanceList defines model for BalanceList.
type BalanceList struct {
	Data []Balance `json:"data"`
}

// BalancePage defines model for BalancePage.
type BalancePage struct {
	Data       []Balance  `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Momentum defines model for Momentum.
type Momentum struct {
	Hash          string  `json:"hash"`
	Height        int64   `json:"height"`
	Producer      string  `json:"producer"`
	ProducerName  *string `json:"producer_name,omitempty"`
	ProducerOwner *string `json:"producer_owner,omitempty"`
	Timestamp     int64   `json:"timestamp"`
	TxCount       int     `json:"tx_count"`
}

// MomentumList defines model for MomentumList.
type MomentumList struct {
	Data       []Momentum `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`

	// Total Total rows matching the query across all pages.
	Total int64 `json:"total"`
}

// Problem RFC 7807 problem details.
type Problem struct {
	// Code Stable application-level error code (extension).
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`
	Status   int32   `json:"status"`

	// Title A short, human-readable summary.
	Title string `json:"title"`

	// Type A URI reference identifying the problem type.
	Type string `json:"type"`
}

// Status Indexer sync state derived from the database.
type Status struct {
	// IndexerLagSeconds Server clock minus latest_timestamp. Grows when the indexer falls behind.
	IndexerLagSeconds int64 `json:"indexer_lag_seconds"`

	// LatestHeight Height of the most-recently-indexed momentum (0 if empty).
	LatestHeight int64 `json:"latest_height"`

	// LatestTimestamp Unix-seconds timestamp of the latest momentum.
	LatestTimestamp int64  `json:"latest_timestamp"`
	Version         string `json:"version"`
}

// Token defines model for Token.
type Token struct {
	Decimals            int     `json:"decimals"`
	Domain              *string `json:"domain,omitempty"`
	HolderCount         int64   `json:"holder_count"`
	IsBurnable          bool    `json:"is_burnable"`
	IsMintable          bool    `json:"is_mintable"`
	IsUtility           bool    `json:"is_utility"`
	LastUpdateTimestamp int64   `json:"last_update_timestamp"`

	// MaxSupply Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	MaxSupply     Amount `json:"max_supply"`
	Name          string `json:"name"`
	Owner         string `json:"owner"`
	Symbol        string `json:"symbol"`
	TokenStandard string `json:"token_standard"`

	// TotalBurned Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	TotalBurned Amount `json:"total_burned"`

	// TotalSupply Raw int64 token amount (no decimals applied) serialized as a
	// JSON string. Strings avoid JavaScript Number precision loss for
	// values above 2^53-1 — ZNN total supply already exceeds that.
	TotalSupply      Amount `json:"total_supply"`
	TransactionCount int64  `json:"transaction_count"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	Data       []Token    `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// SortParam defines model for SortParam.
type SortParam string

// RateLimited RFC 7807 problem details.
type RateLimited = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAccountBlocksParams defines parameters for ListAccountBlocks.
type ListAccountBlocksParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort direction over the endpoint's documented sort column. Defaults vary per endpoint.
	Sort *ListAccountBlocksParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListAccountBlocksParamsSort defines parameters for ListAccountBlocks.
type ListAccountBlocksParamsSort string

// ListAccountTransactionsParams defines parameters for ListAccountTransactions.
type ListAccountTransactionsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort direction over the endpoint's documented sort column. Defaults vary per endpoint.
	Sort *ListAccountTransactionsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListAccountTransactionsParamsSort defines parameters for ListAccountTransactions.
type ListAccountTransactionsParamsSort string

// ListMomentumsParams defines parameters for ListMomentums.
type ListMomentumsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort direction over the endpoint's documented sort column. Defaults vary per endpoint.
	Sort *ListMomentumsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListMomentumsParamsSort defines parameters for ListMomentums.
type ListMomentumsParamsSort string

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListTokenHoldersParams defines parameters for ListTokenHolders.
type ListTokenHoldersParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List account-blocks (transactions)
	// (GET /api/v1/account_blocks)
	ListAccountBlocks(w http.ResponseWriter, r *http.Request, params ListAccountBlocksParams)
	// Get an account-block by hash
	// (GET /api/v1/account_blocks/{hash})
	GetAccountBlock(w http.ResponseWriter, r *http.Request, hash string)
	// Get account info
	// (GET /api/v1/accounts/{address})
	GetAccount(w http.ResponseWriter, r *http.Request, address string)
	// List balances for an account
	// (GET /api/v1/accounts/{address}/balances)
	GetAccountBalances(w http.ResponseWriter, r *http.Request, address string)
	// List transactions involving an address
	// (GET /api/v1/accounts/{address}/transactions)
	ListAccountTransactions(w http.ResponseWriter, r *http.Request, address string, params ListAccountTransactionsParams)
	// List momentums
	// (GET /api/v1/momentums)
	ListMomentums(w http.ResponseWriter, r *http.Request, params ListMomentumsParams)
	// Get the most-recently-indexed momentum
	// (GET /api/v1/momentums/latest)
	GetLatestMomentum(w http.ResponseWriter, r *http.Request)
	// Get a momentum by height
	// (GET /api/v1/momentums/{height})
	GetMomentumByHeight(w http.ResponseWriter, r *http.Request, height int64)
	// Indexer sync status
	// (GET /api/v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// List ZTS tokens
	// (GET /api/v1/tokens)
	ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams)
	// Get a ZTS token by ZTS identifier
	// (GET /api/v1/tokens/{token_standard})
	GetToken(w http.ResponseWriter, r *http.Request, tokenStandard string)
	// Richlist for a token
	// (GET /api/v1/tokens/{token_standard}/holders)
	ListTokenHolders(w http.ResponseWriter, r *http.Request, tokenStandard string, params ListTokenHoldersParams)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccountBlocks operation middleware
func (siw *ServerInterfaceWrapper) ListAccountBlocks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountBlocksParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountBlocks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBlock operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBlock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBlock(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, address)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBalances operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBalances(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBalances(w, r, address)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccountTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListAccountTransactions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountTransactionsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountTransactions(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMomentums operation middleware
func (siw *ServerInterfaceWrapper) ListMomentums(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMomentumsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMomentums(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLatestMomentum operation middleware
func (siw *ServerInterfaceWrapper) GetLatestMomentum(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestMomentum(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMomentumByHeight operation middleware
func (siw *ServerInterfaceWrapper) GetMomentumByHeight(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "height" -------------
	var height int64

	err = runtime.BindStyledParameterWithOptions("simple", "height", r.PathValue("height"), &height, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "height", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMomentumByHeight(w, r, height)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTokens operation middleware
func (siw *ServerInterfaceWrapper) ListTokens(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokensParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokens(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToken operation middleware
func (siw *ServerInterfaceWrapper) GetToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token_standard" -------------
	var tokenStandard string

	err = runtime.BindStyledParameterWithOptions("simple", "token_standard", r.PathValue("token_standard"), &tokenStandard, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token_standard", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToken(w, r, tokenStandard)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTokenHolders operation middleware
func (siw *ServerInterfaceWrapper) ListTokenHolders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token_standard" -------------
	var tokenStandard string

	err = runtime.BindStyledParameterWithOptions("simple", "token_standard", r.PathValue("token_standard"), &tokenStandard, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token_standard", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokenHoldersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokenHolders(w, r, tokenStandard, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/account_blocks", wrapper.ListAccountBlocks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/account_blocks/{hash}", wrapper.GetAccountBlock)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/accounts/{address}", wrapper.GetAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/accounts/{address}/balances", wrapper.GetAccountBalances)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/accounts/{address}/transactions", wrapper.ListAccountTransactions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums", wrapper.ListMomentums)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums/latest", wrapper.GetLatestMomentum)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums/{height}", wrapper.GetMomentumByHeight)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tokens", wrapper.ListTokens)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tokens/{token_standard}", wrapper.GetToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tokens/{token_standard}/holders", wrapper.ListTokenHolders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fv9bttGtn+VA3aB2liKkh0nTVUUCyftNinaNDdysUAjrzQij8RphjPMzFC2bBjYh7jPcB9sn+RiPih+",
	"iLKkbONN7t38E0vkzJxz5ne+j26DWGS54Mi1Coa3QU4kyVCjtJ9ekwW+Nt+YDwmqWNJcU8GDYXDSmxGF",
	"CeRkgcCLbIYygu9wTgqmFWgBJxH8UuiemPck4QuEmJEsxwQUZcg1W0VBGFCz0/sC5SoIA04yDIaB2TAI",
	"AxWnmBF3rt00GJ6EAV6TLGeoguHbk8swyCinWZHZR3qVm+WUa1ygDO7uQkv+iN5sY+GlxkxBjtIysaYe",
	"Hg9CyMi12RlOB4N/gY+JojdbmHk8aHDzeGDYcYcGw9PBYCdzIyH1FsbMI0ioxNh8AWKJEnSKgDzJBeX6",
	"SwWJiIsMuTaMmLdjwYqM125wSeTKyqZctI1Ps7zBInJD9NuAqDgILWXB5ZoDpSXli+DOcCBR5YIrtFB7",
	"QzT+RDOqMTEfY8E1cm3+JHnOaEwMK/1cihnD7M+/K8Pobe3UP0mcB8Pgi36F5757qvqv3Sp3alNUF0JA",
	"RvgKJL4vUGkFc2GERRWoYvY7xjoK7sLgV04KnQpJbx6WvJ+pUpQvQEigfEkYTWCGRJr7FO+QRxYJfh9z",
	"zHkci8LRlUuRo9TUiZckiURl/2zdRBjMmIjfTdYL50JmRDu0PTkLNsFniGS4IBo7t/MPqeATpYnUE00z",
	"VJpk+Z67z6lUekJiTZc4IfvStECOiqrJeyUnM8IIj3GX4M8zy3Nt8Q3nhy9m5APIzYsZo/HkHa46hWi4",
	"kBgjXTrA7UeJWaU8LvdbYRg+/Byz6pBzrLK/L6g0h7xdg7EJve5b6L7YGgktHmpCaEmxMkLCKrZhxOvL",
	"M0PGph09By0JV8SZ0SPiXu5ZooFy+A254MaYFoT1GCYLlJCJBNlxBL9wHHP/pgKkOkUJBBTyBI4c24Ya",
	"OImis2Oj3wQ8pXD0OIqeHn8DZMyNTBlqbBBClbXmGdFxigkcmT3DcvUx5ITKaMyD8AATQLJS+/cDQMWA",
	"tfiVHzu97LQXRJMttkLFyBPC9UTMO99IiUq7HyBdpPtqG+V5ob0QqBEiYa8bwumkrELCdxiLBBMwdl+S",
	"WIPdUMHRj6NfXoHD0zFcpcjt1VCe4DVKcydiwY3TcDeGOhVJFHQA0T3qpCQTxlEX2WSrKKo3DpHJetWh",
	"9tkADJOJV4fJrFSeDbq0mNwHOuvCjI/gCZFdvLfMhuW/LY9OPjZF0oDsGjxhzRR5FdhlJX6iqsO9lgCn",
	"JqTcqUZ1o3O3Po9ISVZOvgvKiUPejsiherMtLEtRY69OztZ638T7G3IFFgAuzgAnHDjiAhKMaUaYAhv4",
	"YHIMCiUlzKKcKGO1rFK4S4xgZP9XQJaCJvAjWZKRPQhe2aQBcokxVcauMaFs+DU2kU6BCshMLBFO//74",
	"Ue8E/vmP/4bfXr0CLTRhoIo8ZysgTCJJVoDXMWJi7CLRzvbVbFJwMqj+GTHkRGuUhs+/9/7ydtD7+vLP",
	"fwrCTYA+qyKBA6KpDwofijwhGpODdfFQHarw3lpZEb6Voi4AeRH9AVpRCntDIbqAfQ8pJun7WKQ8qG6+",
	"QMJ0usmK0kQXqp5piXddGVbzTL+q66Cfva3cPKr0OHVlejI7I49O5/N//uN/Ok6t++V6sn766OzxZbiJ",
	"6HWSO+j0NFIkRYyyTcPNyfv3284v10xcfnp7zxviiru9N11TXQ3rfHxV2pEuZjrU87rKq2rbPLrsTOkb",
	"zq70UN7L1Z3beteahO672D9AO9cY+ffqxOvGUU1+cq/4rRpRV/xSVmaab9saTJeJ1YRtusgL64ekuFIu",
	"EjdpugnybHkESCyNNyOM2eKSipouaas+7ECFL47Va0uOvE5h+brCpnf/63P46ungK/D1CkhQE8oskU2Z",
	"mqi3o76kyYwh1CofPYZLZIBSCglmERzhtUZu/Ppxi/egqBdTulTYkdOVj6VFRnjP+HxLAV7njDg8gMox",
	"pnMagxaufiPiuJASeYxRl3On3Pi+GLuO+fXNS5A4R7saaIJc0/mqvOH1Sc0T1ndZSNp1YM1uV8I4G5y0",
	"YPDotNuSUM06aVWpkDpsS0YVWUbkqi36X3eJvkzpDpNIiSOzun0kmYlCD2eMcOul7pdSC+4+Wne8h/f5",
	"sNFauK0ar8/E1IrHYNYjJCjpEhOYS5FZ6o3pmRGFm/D3edyEkcVEYSx40nHECOUSJcQ2188oLxQwolHV",
	"Cl8R/GANxUaCOCeMKZhhSnnSEtzj/TyMP6ryuk3iXtjvQcxdAiqU7kmMbeG654hIoMyV4GgAdA6Y5Xp1",
	"vK/But+BtwWxSeCvnF73vGxh/V5JsFu/prBN1IHeeIlSeddRR2iCy93xU1POHZyFnWipDu1C7YWJwTs8",
	"s0+xaqFJvZgiMkJ5d01EsATlQaVcqiazQnJjNGpbzoRgSLh/IaNc3/tCoSmjetX9vJZNHJzeZOR64lK9",
	"/fOprXHf9nBPrbKZYHsWKRqBqFYnN5xf1/99fXNWsOtu62p8tZX3IdVWt+pQMdQqhgcAom2A20miFe5a",
	"YGEF1VK8LXIbV9hEWxNaDRy1JLUNQy3Ad/G8Vev+gJjYae+/MyA20MW4kFSvRmZHx4TrEJ0XLnl0n/5a",
	"XvyPf7sI2tXNF6PTx096ii44JvDj3y6MF9OYwJISmMZZ0v/9SveoUgVOI3hOpKSoYKqK2TSEKV7n5j9K",
	"9DQcc8ITIBx+MafDaTQAlZMYewpzIonZc6pikeMUYkZo5ko1VhjWaFhSK1SmWueuK0b5XJR9NxLbi/Pt",
	"Ry4y78hkbyGCMCgk80vVsN9fUJ0WsygWWX9w/ejJo6/7rQUbpd43SJKe4GwFLy4uXsP565dVA7W5tgoc",
	"wEqf9IjqlRXi4Zjj0mQCZZcTMmqiY1e7L3iCktn46bVQeiFRgQuqGVmJQtf7s0SPecmO4yHyXFHR4sbj",
	"qh+N+Zh/8QWYWzCRmgvSzZfnjK07usqRAdM+yWl/edKfggcgEHjm2owGDdTFLNNzHzrazaZjniJJUEZg",
	"9UABkQgNJM1WBgokySjvgtI3ZleJQNWYc+EKjT2DvKrlDCNE2Jd3w4SJbtfcV8plvnguGPMN8ZoAFIKY",
	"zxXqPqMZ1XA0/YtJrr49GReDwemTdaL17ePB1E4FwOlgcAyEJ2MuUReSGx6RL5GJHGF6azAxhLdRFF2G",
	"UCnvEG7NXvYrt2PoKpl3d9NozEeULxj2jNmpUecPMMJ3Gu+b+mxVsvi9hZT54P6yl+CWuWrsdFt7egpH",
	"ZRp4DFdUp+vCrT8qJlJagE6NNhoVt2G4+cPF4eYvl6lNQ7B6P+ZxobTIYGpSwCnMKbLE6TijMXJl/bJP",
	"HqjxxcHPLy+qUQLzoUp1WqptNLEWTg2DQXQSDaxfz5GTnAbD4JH9yhZ4U2sKS2Q3ehX2yQKtFTHG3wrn",
	"ZRIMA+MU6tV5ZfeqJmLedlvz6pV+NTFzF+71cjWfsseCaubj7rI1P3E6GNwzmHDYQMJGv6NjMsErFybA",
	"qLIJRqM9quzYxNngZNtZa+L7jZzULDr9evei+rhI3Q3aO6o7wLeXRlQ+HfZX3CIVjmpxgzo2/ocsXO7a",
	"hM2lOakbUv3blKj0biuyfsAGsDZxZUdrDG4rdfCVvyoo0LLA+qRNO2N5KEx0DtKkWM7QGMtTF/C/AIXB",
	"2UNO27wSTcKdXdQp0WDuIvr46PwBtfWZDSpmKyiLwPvjUvVvfa+nDsp2qGMchYtI/LIvFcyZuIIMtaSx",
	"giNG52gibvjt1av+f43egEKu++VQRTjmdlqnbwJ0sDMwVK+OIWeFgmoQyFVeIigPPBucAbUZ/piXpZCU",
	"KLAhE4iZQrn0PXPPhPMi23RqL3WqWl/bNWq/JsNDKFoXPv0jMNHwZ6hUNXUqb/WBNKomt00t2qk/fd8Z",
	"VTsVyUX8R82sOQS//hikuPLzhWtgh2OuhNQuXPYvwnffj55H8EroMoLExPa/K9MAepXTmDC2GnOTBCsg",
	"kBKezAtma2c2JL9faZ6VXP1RyvOQWlLvO3eA7icfk5Q390lHIyWRFhrVFX8IUuuBzE60tqKgK5uN1aBZ",
	"G1xTaDNFIU3WE9Ocos3O1sBtjdt8A37OGczJXTCsRdoXdZo/FhbD/0Tu/yci9zrAgfKlYEuTo9o6w3qy",
	"5V6tKaG6Wz/Wb4KQCUqHdAdwOCoBPjVrp8cRGEiATqUoFumYGzWaF4xBnBLKnefzpYWpTZbdB1dbmG7T",
	"kJ/XtP6/zEMb8wt7IXl9ZZ80iLPatZZgrb7rRmvfNZz2iuVTukhR6Z7H6rp71hF/l53IMbfxt4k4pIhR",
	"KZPE8RV437BCvSWY+MmStR4PeQA0bMs+N3qFn0+AXFmalCwRZogcyu6sEf3DhMm7O8SH4PXWoe/ekkh5",
	"pc9WL8q+6h5lkfLVvdK4D2pcP4hV211FaUF58JCo9IMD1BkFAlzwHrfp/NIYDSuoz1HFAK+p0gqI9oUd",
	"y+dDJaIVGetQYrdOVYNDOy2/t4Ebkx3uqBCorg1ZhK6NMe2YW4BvgYsr6G1MskwjeC6yvNC1AZoxLxth",
	"QJjgaFPVRKCDTkqdZbE/lgEuEtziSfwIz0fUPH9CB0Ce2zkuXRsT+lQDiI2BpqIRRaAmTfC4SsBO8Px2",
	"MfJFg0awW2uv26IEHFkHkSJLwBb+jkMb63Jo1jzgfPTcprNKk5nt6W8LcV3z8EHj249p3KvZgr3iVV+n",
	"+ZSD1QoZNZz5LzqQ1r9tIuFe/+8mKPZx+huDKJ9GGcqPgHT9rvidjeE+r0Kt+7FPVaYt5f1g7nENNmN9",
	"zIdas/iD0Nd3JmyPYpgrH6CyRq8cbLW7hbClQjvm31/HrEhQwQ1KUVUb77N1LzxBHxn14WdrQuu/47nX",
	"iLqrtbb0U7Wgb2icWltvS7sOTtuAnNrf+9xsReo5uyKrcihEwelg4MtKt2M/GT0OhuNAvBsHd9MIvisD",
	"sDjF+F0rTjMRmtHwLxVM+/YndDfTCEYFdUNIhtp3TxUwukSOSrk9tvUTXnjCPyIm/G+hOuAwQrmkMZpE",
	"hRhyo/YFtTyaZ8hYT+wInOxauSx1stVVEDFhkKAd9sncT8yrcbNhv8/MC6lQevh08HQQ3F3e/W8AAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
