//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for SortParam.
const (
	SortParamAsc  SortParam = "asc"
	SortParamDesc SortParam = "desc"
)

// Valid indicates whether the value is a known member of the SortParam enum.
func (e SortParam) Valid() bool {
	switch e {
	case SortParamAsc:
		return true
	case SortParamDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListMomentumsParamsSort.
const (
	ListMomentumsParamsSortAsc  ListMomentumsParamsSort = "asc"
	ListMomentumsParamsSortDesc ListMomentumsParamsSort = "desc"
)

// Valid indicates whether the value is a known member of the ListMomentumsParamsSort enum.
func (e ListMomentumsParamsSort) Valid() bool {
	switch e {
	case ListMomentumsParamsSortAsc:
		return true
	case ListMomentumsParamsSortDesc:
		return true
	default:
		return false
	}
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Momentum defines model for Momentum.
type Momentum struct {
	Hash          string  `json:"hash"`
	Height        int64   `json:"height"`
	Producer      string  `json:"producer"`
	ProducerName  *string `json:"producer_name,omitempty"`
	ProducerOwner *string `json:"producer_owner,omitempty"`
	Timestamp     int64   `json:"timestamp"`
	TxCount       int     `json:"tx_count"`
}

// MomentumList defines model for MomentumList.
type MomentumList struct {
	Data       []Momentum `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`

	// Total Total rows matching the query across all pages.
	Total int64 `json:"total"`
}

// Problem RFC 7807 problem details.
type Problem struct {
	// Code Stable application-level error code (extension).
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`
	Status   int32   `json:"status"`

	// Title A short, human-readable summary.
	Title string `json:"title"`

	// Type A URI reference identifying the problem type.
	Type string `json:"type"`
}

// Status Indexer sync state derived from the database.
type Status struct {
	// IndexerLagSeconds Server clock minus latest_timestamp. Grows when the indexer falls behind.
	IndexerLagSeconds int64 `json:"indexer_lag_seconds"`

	// LatestHeight Height of the most-recently-indexed momentum (0 if empty).
	LatestHeight int64 `json:"latest_height"`

	// LatestTimestamp Unix-seconds timestamp of the latest momentum.
	LatestTimestamp int64  `json:"latest_timestamp"`
	Version         string `json:"version"`
}

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// SortParam defines model for SortParam.
type SortParam string

// RateLimited RFC 7807 problem details.
type RateLimited = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListMomentumsParams defines parameters for ListMomentums.
type ListMomentumsParams struct {
	// Page 1-based page number. Defaults to 1. Out-of-range clamped silently.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page. Default 50, maximum 200. Out-of-range clamped silently.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort direction over the endpoint's documented sort column. Defaults vary per endpoint.
	Sort *ListMomentumsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListMomentumsParamsSort defines parameters for ListMomentums.
type ListMomentumsParamsSort string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List momentums
	// (GET /api/v1/momentums)
	ListMomentums(w http.ResponseWriter, r *http.Request, params ListMomentumsParams)
	// Get the most-recently-indexed momentum
	// (GET /api/v1/momentums/latest)
	GetLatestMomentum(w http.ResponseWriter, r *http.Request)
	// Get a momentum by height
	// (GET /api/v1/momentums/{height})
	GetMomentumByHeight(w http.ResponseWriter, r *http.Request, height int64)
	// Indexer sync status
	// (GET /api/v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListMomentums operation middleware
func (siw *ServerInterfaceWrapper) ListMomentums(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMomentumsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMomentums(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLatestMomentum operation middleware
func (siw *ServerInterfaceWrapper) GetLatestMomentum(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestMomentum(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMomentumByHeight operation middleware
func (siw *ServerInterfaceWrapper) GetMomentumByHeight(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "height" -------------
	var height int64

	err = runtime.BindStyledParameterWithOptions("simple", "height", r.PathValue("height"), &height, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "height", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMomentumByHeight(w, r, height)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums", wrapper.ListMomentums)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums/latest", wrapper.GetLatestMomentum)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/momentums/{height}", wrapper.GetMomentumByHeight)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fn9bts4En+VgfaAbXGyrXx1uz4sDtnu7aZFuw2aFAtcHES0NLbYUKRKUk6cwMA+xD3DPdg+yWFIyZJl",
	"5aO3aHDXf2rTJOfrx5nfTG6DROWFkiitCca3QcE0y9Gidt+O2RyPaYW+pGgSzQvLlQzGwc5gygymULA5",
	"gizzKeoh/IQzVgprwCrYGcL70g7UbKCZnCMkguUFpmC4QGnFchiEAaebPpeol0EYSJZjMA7owiAMTJJh",
	"zrxcd2kw3gkDvGZ5IdAE47Od8zDIueR5mbuf7LKg41xanKMOVqvQqX/Cb+4y4bXF3ECB2hmx1h4OohBy",
	"dk03w24U/Qk7Lgy/ucOYg2jDmoOIzPFCg/FuFD1o3InS9g7D6CdIucaEFkAtUIPNEFCmheLSfmsgVUmZ",
	"o7RkCO1OlChz2Yrgguml80196C476fiGiShJ6bOAmSQInWbB+doCYzWX82BFFmg0hZIGHdQ+MItvec4t",
	"pvQ1UdKitPSRFYXgCSNTRoVWU4H5Xz8ZMvS2JfUvGmfBOPhm1OB55H81o2N/ykvddNWpUpAzuQSNn0s0",
	"1sBMkbO4AVNOP2Fih8EqDD5KVtpMaX7ztOq948ZwOQelgcsFEzyFKTJN8VSXKIcOCdU9JOYImbCZe8ha",
	"Fagt9941ltnStKOjLvuiQkH5XHJNVp7Vp5p9ynmEHPJOEXrKfFtUxoxToAXu4MV0n+3tzmZ//P7vHqlh",
	"kCGfZ7Zzamd3b//gPAxmSufMevS/2A9aDyPafhghaZOWCequDjc7nz/fJb8+c+ExfXvPDnUl/d1bWyzP",
	"0ViWF107vouqf33GbBtgry8SVcquO/bOe9NAO16VG0Mfg7ZGrVtbHrovsG+5sdvBTZl1cOaUOh/C9Roj",
	"q7UcpjVbOn+yOZfMo/yB19Hs7NrrtNm4q8+i4w1Rm/a4YtMJ13kvqtbZfHO3y9s9MVSWie3EfErLoNWV",
	"gZzZJKOnTYnZpVRgiVbGABPCFSRDGfcx7+EBVFQFtV2PvHq9zqpy0ZbqH35+Bd+9jL6DKsdBipZx4ZTc",
	"9GmiUuypSZZNBUIrWw4ELlAAaq000CF4htcWpeFKPu/YHpTtBNz3hL0623IPIStzJgcaWeo0wOtCMI8H",
	"MAUmfMYT4isu56skKbVGmeAw6BHCpbFMJtgn5uOH16Bxhu408BSl5bNlHeG1pE0J61iWmvcJbOXtxhn7",
	"0U4HBnu7/ZmEW9Grq8mUtmHXM6bMc6aXXdd/fMj1fuFLPVLjiE53RbKpKu14Kph0Vep+L3Xg7n6tbQ/v",
	"q2Ena+d2eKFM8Ro1mKVMgM4jpKj5AlOYaZU77Sn1EAHehj/3py8Em18YTJRMe0ScoCZSlgiVXELOZWlA",
	"MIvGXqxz9hB+cYniKkPpRFYXw4wJYWCKGZdpx3EHj6swlaim6m4qd+TWQc2c2FwZO9CYOLI78EqkkFe5",
	"HZ5FwGeAeWGXzx+bsO4v4F1HbCv4UfLrQeVbWO+rFfbn1xp2lfrCarxAbarS0UZoiouH+dOmn3ssC3vR",
	"0gjdRi3lBExKze3yhAqkx5znhIelp37+28+1bW9+Ow26vPLoZPfgxcDwucQU3vx2ShikXmDBGcRJno4+",
	"XdkBN6bEeAivmNYcDcSmnMYhxHhd0H+c2TicSCZTYBLek3TYHUZgCpbgwCC1knRnbBJVYEyNE8+HE1k3",
	"C2SWV7VxfGZt4XkwlzNVM22WOJRWDYdUeQVDPZirIAxKLaqjZjwazbnNyukwUfkout57sff9qHNgi2R/",
	"QJYOlBRLODo9PYbD49dNy7R5tnn24LzPBswMSEPNEjueSFxQHa/7Gsg51TbjLiplilq47HesjJ1rNOBL",
	"omBLVdp2R8bsRNbmeBuGlVVcdaypaNJoOJET+c03QFGgPOtLLC0eCrHu4YxXA+IRK/hosTOKocIrMPjR",
	"NxaEBu4zTnxYJX53WTyRGbKU+vxTaj4MMI2wgaTpkqDA0pzLPij9jW7VCNxMpFS+hRkQ8pomE04Q4bG2",
	"kxFUm9bWN1SPFl4pIaoWuOUAg6BmM4N2JKjdhGfx34ka/bAzKaNo98WaJv1wEMVuDgC7UfQcmEwnUqMt",
	"tSQbUS5QqAIhviVMjOFsOByeh9Bw0THc0l1uyd8YguNdq1U8nMgTLucCB0SkW9pVAsj5/sVXbbxY1ib+",
	"w0GKvvhPLgj+GCHHQHxXQxrDs5rEPYcrbjNgE/nm5P2vtaiEae0AGtNrpCfuiih98FWUPnmeFYfg3v1E",
	"JqWxKoeYCFwMM44i9W9c8ASlccSgKv2cGqfg3evTZnhAXxqi0nna9BJbyXAcRMOdYUT7VYGSFTwYB3tu",
	"iditzVwqrJFdp3+3OMeeMvfBOc2sC4UBpVPUHsY+Z8Ozal5Ddpskfj4kiCHYTKtynk0kBWpWCgFJxrj0",
	"Xq3wFDsP+S8eULF3DJEFF53XaTAOqM96t9Y13BjAnfV3Rs2WUTOgW4WP2tyMwx5xoBkxrc4745rdKLpn",
	"DvJl84+NlrNnCFK9akxBcON4yTpkbjizH+3cJWKt82iDxdKh3e8fPtQeSrVLrwtNu+ienZOHKgJdRbXR",
	"kuobmzve0Kyd04VbaB15jvAgaAl4GZ9naOygwuqa8EC9aT/aJ3LWIo8TmTEDUlmi3wkaQzlDLmFKRNTA",
	"Em0fRn9B+9apte7onwANvdO6Pnr3XyMg2n/KUd6vqpVpMrZAmCJKqAk1uf7r4/IXtI8g9V+C11uPvlUL",
	"sVvgqUP64/KopsKdNOcGy5TDm9KwZs0No7a6xI1J85/sNZ4kq92F42rg3HJ7BeXoKVFZ9XrcJwUGUsmB",
	"xDmzfEFJwznq//GJAV5zYw0wwjuzVT1/ohfGGjXWVOLhN9XMeh7M/FUO3GrGvagQuG31xaHnrnFPqwk/",
	"gFRXMNgaPlDXp/KitK2Zx0TW3Q8woSTCH7//C1KFHjoZ95nlnyiVBKlSvKOSVFOXr/jyKgk9AHnlRm+2",
	"Ndn5XyUQWzOocoNFoGUVeDL3F5+bO2FzKK7Ysm4sDPUyFUu9nVSzsUkwngTqchKs4iH8VMczyTC57ISd",
	"Ak6v6VsD8UgjS5c38RBOSu4b2ZnScPnSgOALlGiMv8PcgYOjSvGvCITqr2E9QDhBveAJdaLASN1hNzod",
	"NlcZRBkLe+LgzupFXc02Zb1VCROQomsY6aFujCzGo5GgDZkydvwyehkFq/PVfwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
