#!/usr/bin/env bash
# Regenerate docs/schema/_generated.md by running tbls against a freshly
# migrated test database.
#
# Usage:
#   scripts/docs/gen-schema-tbls.sh
#
# Required env:
#   TEST_DATABASE_URL  postgres connection string to a DB that already has
#                      the latest migrations applied (e.g. nom_indexer_test
#                      from Docker Compose).
#
# tbls is installed via the Go tooling chain:
#   go install github.com/k1LoW/tbls@latest
set -euo pipefail

if [ -z "${TEST_DATABASE_URL:-}" ]; then
  echo "TEST_DATABASE_URL not set. Example:" >&2
  echo "  TEST_DATABASE_URL='postgres://postgres:nomIndexerPass123@localhost:5432/nom_indexer_test?sslmode=disable' \\" >&2
  echo "    scripts/docs/gen-schema-tbls.sh" >&2
  exit 1
fi

if ! command -v tbls >/dev/null 2>&1; then
  echo "tbls not found in PATH. Install with:" >&2
  echo "  go install github.com/k1LoW/tbls@latest" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_DIR="$REPO_ROOT/docs/schema/_generated"
SINGLE_OUT="$REPO_ROOT/docs/schema/_generated.md"

# tbls emits one file per table plus a README; we consolidate to a single
# Markdown page so the mkdocs nav stays flat. The per-table prose pages
# (hand-written) are authoritative; this file is the columns/indexes appendix.
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

cd "$TMPDIR"
tbls doc -t md --rm-dist "$TEST_DATABASE_URL" ./out >/dev/null

{
  echo "# Generated column reference (tbls)"
  echo
  echo "> Auto-generated by \`scripts/docs/gen-schema-tbls.sh\` from the test"
  echo "> database. Hand-written per-table pages in this folder are"
  echo "> authoritative for semantics; this file is the columns/indexes"
  echo "> appendix."
  echo
  if [ -f "out/README.md" ]; then
    cat "out/README.md"
    echo
  fi
  for f in out/*.md; do
    case "$(basename "$f")" in
      README.md|schema.json) ;;
      *)
        echo
        cat "$f"
        echo
        ;;
    esac
  done
} > "$SINGLE_OUT"

echo "wrote $SINGLE_OUT"
